export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS'
export const CHOOSED_ADDRESS = 'CHOOSED_ADDRESS'
export const EXPRESS_MISSION_INFO = 'EXPRESS_MISSION_INFO'
export const MEMBER_INFO = 'MEMBER_INFO'

