export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS'
export const GET_MEMBER_INFO = 'GET_MEMBER_INFO'
export const CHOOSED_ADDRESS = 'CHOOSED_ADDRESS'
export const EXPRESS_MISSION_INFO = 'EXPRESS_MISSION_INFO'

